### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by simon020286** [wokim/mongoose-transaction-plugin#1]
I have this error when run postinstall
> tsc -p $(pwd)

error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: '$(pwd)'.
npm WARN mongodb-core@1.2.32 requires a peer of kerberos@~0.0 but none was insta
lled.
npm WARN ClasseWeb@0.0.0 No repository field.
npm WARN ClasseWeb@0.0.0 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "mongoose-transaction-plugin"
npm ERR! node v5.4.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! mongoose-transaction-plugin@0.0.5 postinstall: `tsc -p $(pwd)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongoose-transaction-plugin@0.0.5 postinstall script 'tsc
 -p $(pwd)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongoose-transaction-
plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p $(pwd)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongoose-transaction-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongoose-transaction-plugin
npm ERR! There is likely additional logging output above.

**Comment by wokim** [comment]
we are fixing now. sorry :'(

**Comment by wokim** [comment]
0.0.6 released
